config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  resources :parking_lots
  resources :locations
  devise_for :admins, skip: :registrations
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', as: 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', as: 'admin_registration'
  end
  resources :attractions
  get 'about' => 'static_pages#about', as: 'about'
  get 'nearby' =>'maps#nearby_mobile', as: 'nearby'

  root 'maps#map'

end

app/models/parking_lot.rb
class ParkingLot < ActiveRecord::Base
  geocoded_by :address
  # auto-fetch coordinates and the condition is for preventing fetching the same address more than once
  after_validation :geocode, if: :address_changed?
end

app/controllers/parking_lots_controller.rb
class ParkingLotsController < ApplicationController
  def index
    @parking_lots = ParkingLot.all
  end

  def new
    @parking_lot = ParkingLot.new
    respond_to { |format| format.js }
  end

  def show
    @fields = [
      :name,
      :address,
      :latitude,
      :longitude,
      :hours,
      :rates
    ]
    @parking_lot = ParkingLot.find(params[:id])
    respond_to { |format| format.js }
  end

  def edit
    @parking_lot = ParkingLot.find(params[:id])
  end

  def create
    @parking_lot = ParkingLot.new(parking_lot_params)
    if @parking_lot.save
      flash.now[:notice] = 'Parking lot saved'
    end
    respond_to { |format| format.js }
  end

  def destroy
    @parking_lot = ParkingLot.find(params[:id])
    @parking_lot.destroy
    respond_to { |format| format.js }
  end

  def update
    @parking_lot = ParkingLot.find(params[:id])
    if @parking_lot.update(parking_lot_params)
      flash.now[:notice] = 'Parking lot saved'
    end
    respond_to { |format| format.js }
  end

  private

  def parking_lot_params
    params.require(:parking_lot).permit(
      :name,
      :address,
      :latitude,
      :longitude,
      :hours,
      :rates
      )
  end
end

app/views/parking_lots/_form.html.erb
<%= form_for @parking_lot, remote: true, html: { multipart: true } do |f| %>
  <% if @parking_lot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parking_lot.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @parking_lot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :hours %><br>
    <%= f.text_field :hours %>
  </div>
  <div class="field">
    <%= f.label :rates %><br>
    <%= f.text_field :rates %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parking_lots/_info_window.html.erb
  <h3><%= location.name %></h3>
  <ul>
    <li><%= location.address %></li>
    <li><%= location.hours %></li>
    <li><%= location.rates %></li>
  </ul>

app/views/parking_lots/_mobile_info_window.html.erb
  <h3><%= location.name %></h3>
  <ul>
    <li><%= location.address %></li>
    <li><%= location.hours %></li>
    <li><%= location.rates %></li>
  </ul>

app/views/parking_lots/_parking_lot.html.erb
<tr id=<%= dom_id(parking_lot) %>>
  <td><%= parking_lot.name %></td>
  <td><%= link_to 'Show', parking_lot, remote: true %></td>
</tr>

app/views/parking_lots/create.js.erb
$('#sidebar').empty();
$('tbody.parking-lots').append('<%= j render(@parking_lot) %>');

app/views/parking_lots/destroy.js.erb
$("#<%= j dom_id(@parking_lot) %>").remove();
$('#sidebar').empty();

app/views/parking_lots/edit.js.erb
$('#sidebar').empty().append("<%= j render('form') %>");

app/views/parking_lots/index.html.erb
<h1>Parking Locations</h1>

<%= link_to 'New Parking Lot', new_parking_lot_path, remote: true %>

<br>
<br>

<row>
  <div class="columns large-4">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody class="parking-lots">
        <%= render @parking_lots %>
      </tbody>
    </table>
  </div>

  <div class="columns large-8">
    <div id="sidebar"></div>
  </div>
</row>

app/views/parking_lots/new.js.erb
$("td:contains('Show')").show();
$('#sidebar').empty().append("<%= j render('form') %>");

app/views/parking_lots/show.js.erb
$("td:contains('Show')").show();
$('#<%= dom_id(@parking_lot) %>').find("td:contains('Show')").hide();
$('#sidebar').empty().append(
  "<%= j render(
  partial: 'layouts/global_show',
  locals: { fields: @fields, record: @parking_lot }) %>"
);

app/views/parking_lots/update.js.erb
$("#<%= j dom_id(@parking_lot) %>").replaceWith("<%= j render(@parking_lot) %>");
$("#<%= j dom_id(@parking_lot) %>").find("td:contains('Show') a").click();