config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  resources :parking_lots
  resources :locations
  devise_for :admins, skip: :registrations
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', as: 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', as: 'admin_registration'
  end
  resources :attractions
  get 'about' => 'static_pages#about', as: 'about'
  get 'nearby' =>'maps#nearby_mobile', as: 'nearby'

  root 'maps#map'

end

app/views/layouts/_all_attractions.html.erb
<%= render(
      partial: 'attraction',
      collection: @attractions,
      spacer_template: "attraction_divider") %>

app/views/layouts/_global_show.html.erb
<br>

<%=
  link_to 'Edit',
  public_send("edit_#{record.class.to_s.underscore}_path"),
  remote: true
%> |
<%=
  link_to 'Delete',
  public_send("#{record.class.to_s.underscore}_path"),
  method: :delete,
  remote: true,
  data: { confirm: "Are you sure?" }
%>
<br><br>


<% fields.each do |field| %>
  <% if field.to_s.chars.last(3).join == '_id' %>
    <% base_name = field.to_s.chomp('_id') %>
    <p>
      <strong><%= base_name.capitalize %>:</strong>
      <%= record.public_send(base_name).name %>
    </p>
  <% else %>
    <p>
      <strong><%= field.to_s.capitalize %>:</strong>
      <%= record.public_send(field) %>
    </p>
  <% end %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= flash_class(name) %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close alert-box-close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1>
        <a href="http://www.seattleattractions.com/"><%= image_tag("PSAC_logo_small.jpg") %></a>
      </h1>
    </li>
  </ul>

  <section class="top-bar-section show-for-medium-up">

    <ul class="left">
      <li><%= link_to "Map", root_path, 'data-no-turbolink' => true %></li>
      <li><a href="http://www.seattleattractions.com/">Seattle Attractions Website</a></li>
    </ul>

  <% if admin_signed_in? %>
      <ul class="right">
        <%= render 'layouts/navigation_links' %>
      </ul>
  </section>
  <% end %>
</nav>

app/views/layouts/_navigation_links.html.erb
<li class="has-dropdown">
  <a href="#">Admin Resources</a>
  <ul class="dropdown">
    <li><%= link_to 'Map', root_path, 'data-no-turbolink' => true %></li>
    <li><%= link_to 'Attractions', attractions_path %></li>
    <li><%= link_to 'Parking Lots', parking_lots_path %></li>
    <li><%= link_to 'Restaurants', restaurants_path %></li>
    <li><%= link_to 'Locations', locations_path %></li>
    <li><%= link_to 'Sign Out',
      destroy_admin_session_path,
      method: :delete,
      data: { confirm: 'Are you sure?' } %>
    </li>
  </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, maximum-scale = 1.0" />
  <%= favicon_link_tag 'attractionmarkersm.png' %>
  <title>Map - Seattle Attractions</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,700' rel='stylesheet' type='text/css'>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'>
  </script>
  <script type="text/javascript"
    src="//maps.googleapis.com/maps/api/js?AIzaSyBUMYBPxCOmXQ4DWrrNITJ24srStv6v6xY">
  </script>

</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>

  <%= yield %>

</body>
</html>