config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  resources :parking_lots
  resources :locations
  devise_for :admins, skip: :registrations
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', as: 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', as: 'admin_registration'
  end
  resources :attractions
  get 'about' => 'static_pages#about', as: 'about'
  get 'nearby' =>'maps#nearby_mobile', as: 'nearby'

  root 'maps#map'

end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :detect_device
  before_action :authenticate_admin!
  skip_before_action :authenticate_admin!, only: [:show, :index]

  def index
    respond_to do |format|
      format.html.phone do
        @attractions = Attraction.alphabetize.all
      end
      format.html.desktop do
        authenticate_admin!
        @attractions = Attraction.alphabetize.all
      end
    end
  end

  def show
    @device = 'others'
    respond_to do |format|
      format.html.phone do
        @attraction = Attraction.find(params[:id])
      end

      format.html.desktop do
        authenticate_admin!
        @fields = [
          :name,
          :address,
          :phone,
          :location_id,
          :description,
          :latitude,
          :longitude,
          :website,
          :icon,
          :coupon_url
        ]
        @attraction = Attraction.find(params[:id])
      end

      format.js.desktop do
        authenticate_admin!
        @fields = [
          :name,
          :address,
          :phone,
          :description,
          :latitude,
          :longitude,
          :website,
          :icon,
          :coupon_url
        ]
        @attraction = Attraction.find(params[:id])
      end
    end
  end

  def new
    @attraction = Attraction.new
    @locations = Location.all

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @attraction = Attraction.new(attraction_params)
    respond_to do |format|
      if @attraction.save
        format.html { redirect_to attractions_path, notice: 'Attraction saved' }
        format.js { flash.now[:notice] = 'Attraction saved' }
      else
        format.html { render :new }
        format.js
      end
    end
  end

  def edit
    @attraction = Attraction.find(params[:id])
    @locations = Location.all

    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @attraction = Attraction.find(params[:id])
    respond_to do |format|
      if @attraction.update(attraction_params)
        format.html { redirect_to attractions_path, notice: 'Article updated' }
        format.js { flash.now[:notice] = 'Article updated' }
      else
        format.html { render :edit }
        format.js
      end
    end
  end

  def destroy
    @attraction = Attraction.find(params[:id])
    @attraction.destroy
    respond_to do |format|
      format.html do
        redirect_to attractions_path, notice: 'Attraction destroyed'
      end
      format.js { flash.now[:notice] = 'Attraction destroyed' }
    end
  end

  private

  def attraction_params
    params.require(:attraction).permit(
      :name,
      :description,
      :latitude,
      :longitude,
      :website,
      :location_id,
      :address,
      :icon,
      :phone,
      :coupon_url)
  end

  def detect_device
    case request.user_agent
    when /iPhone/i
      request.variant = :phone
    when /Android/i && /mobile/i
      request.variant = :phone
    when /Windows Phone/i
      request.variant = :phone
    else
      request.variant = :desktop
    end
  end

end

app/views/attractions/_attraction.html.erb
<tr id=<%= dom_id(attraction) %>>
  <td><%= attraction.name %></td>
  <td><%= link_to 'Show', attraction, remote: true %></td>
</tr>

app/views/attractions/_form.html.erb
<%= form_for @attraction, remote: true, html: { multipart: true } do |f| %>
  <% if @attraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attraction.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @attraction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.telephone_field :phone %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.collection_select(:location_id, @locations, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.url_field :website %>
  </div>
  <div class="field">
    <%= f.label :icon %><br>
    <%= f.file_field :icon %>
  </div>
  <div class="field">
    <%= f.label :coupon_url %><br>
    <%= f.text_field :coupon_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attractions/_info_window.html.erb
<div class="infowindow">
  <h3><%= location.name %></h3>
  <p><%= location.address %></p>
  <%= image_tag(location.icon.url(:map_icon)) %>
  <ul class="no-bullet">
    <li><%= number_to_phone(location.phone, area_code: true) %></li>
    <li><%= link_to("Website", location.website, :target => "_blank") %></a></li>
    <li><%= link_to("Get Directions", "https://www.google.com/maps/dir/Current+Location/#{location.latitude},#{location.longitude}", :target => "_blank") %></li>
  </ul>
  <p class="text-left"><%= location.description %> </p>
  <% unless location.coupon_url.empty? %>
    <%= link_to("Print Coupon", location.coupon_url, class: "button radius button right") %>
  <% end %>


</div>

app/views/attractions/_mobile_info_window.html.erb
<div class="mobile-infowindow">
  <h1><%= link_to(location.name, location, 'data-no-turbolink' => true) %></h1>
  <p><%= location.address %></p>
  <p><%= number_to_phone(location.phone, area_code: true) %></p>
  <p><%= link_to("Website", location.website, :target => "_blank") %></a></p>
  <p><%= link_to("Get Directions", "https://www.google.com/maps/dir/Current+Location/#{location.latitude},#{location.longitude}", :target => "_blank") %></p>
  <p><%= location.description %></p>
</div>

app/views/attractions/create.js.erb
$('#sidebar').empty();
$('tbody.attractions').append('<%= j render(@attraction) %>');

app/views/attractions/destroy.js.erb
$("#<%= j dom_id(@attraction) %>").remove();
$('#sidebar').empty();

app/views/attractions/edit.js.erb
$('#sidebar').empty().append("<%= j render('form') %>");

app/views/attractions/index.html+phone.erb
<div class="mobile-paragraph">
<p>
 <%= image_tag("seattlebrochure_small.png", :alt => "Seattle Premier Attractions Brochure", :class => "brochure") %>
 <br>Pick up this guide for coupons, maps and more information on Premier Attractions.
</p><br>
</div>

<div class="small-home">
<ul class="no-bullet">
  <% @attractions.each do |attraction| %>
    <li><%= link_to attraction.name, attraction %></li>
    <hr>
  <% end %>
  <li><%= link_to 'Nearby Attractions', nearby_path, 'data-no-turbolink' => true %></li>
</ul>
</div>

<a class="mobile-paragraph" href="http://www.seattleattractions.com/"> < Back to Seattle Attractions Website</a>

app/views/attractions/index.html.erb
<h1>Attractions</h1>

<%= link_to 'New Attraction', new_attraction_path, remote: true %>

<br>
<br>

<row>
  <div class="columns large-4">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody class="attractions">
        <%= render @attractions %>
      </tbody>
    </table>
  </div>

  <div class="columns large-8">
    <div id="sidebar"></div>
  </div>
</row>

app/views/attractions/new.js.erb
$("td:contains('Show')").show();
$('#sidebar').empty().append("<%= j render('form') %>");

app/views/attractions/show.html+phone.erb
<div id="mobile-show">
<h1><%= @attraction.name %></h1>
<p><%= @attraction.description %></p>
<p><%= @attraction.address %> </p>
<p><%= link_to("Get Directions", "https://www.google.com/maps/dir/Current+Location/#{@attraction.latitude},#{@attraction.longitude}", :target => "_blank") %></p>
<p><%= number_to_phone(@attraction.phone, area_code: true) %></p>
<p><%= link_to("Website", @attraction.website, :target => "_blank") %></p>
</div>

<div id="mobile_show_map" style="width:90%; height:50%; padding:1em; margin: 0 auto;"></div>

<script type="text/javascript">
  $(function () {
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'mobile_show_map'}},
    function(){
      var markers = handler.addMarkers([
        {"lat": <%= @attraction.latitude %>,
         "lng": <%= @attraction.longitude %>,
         "picture":
         {"url": '<%= asset_path('attractionmarkersm.png') %>',
          "width": 30,
          "height": 30},
         "infowindow": '<h1><%= @attraction.name %></h1> <%= link_to("Get Directions", "https://www.google.com/maps/dir/Current+Location/#{@attraction.latitude},#{@attraction.longitude}", :target => "_blank") %>'
        }
      ]);
      handler.map.centerOn(markers[0]);
      handler.getMap().setZoom(14);
    });
  });
</script>

app/views/attractions/show.js.erb
$("td:contains('Show')").show();
$('#<%= dom_id(@attraction) %>').find("td:contains('Show')").hide();
$('#sidebar').empty().append(
  "<%= j render(
  partial: 'layouts/global_show',
  locals: { fields: @fields, record: @attraction }) %>"
);

app/views/attractions/update.js.erb
$("#<%= j dom_id(@attraction) %>").replaceWith("<%= j render(@attraction) %>");
$("#<%= j dom_id(@attraction) %>").find("td:contains('Show') a").click();